EntAssignment/EntAssignment/Models/CategoryViewModel.cs
using EntAssignment.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EntAssignment.Models
{
    public class CategoryViewModel
    {
        public category c {get;set;}
        public blog fb { get; set; }
        public List<blog> b {get; set;}

        public CategoryViewModel()
        {
            this.c = new category();
            this.fb = new blog();
            this.b = new List<blog>();
        }
    }
}

EntAssignment/EntAssignment/Models/blogViewModel.cs
using EntAssignment.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EntAssignment.Models
{
    public class blogViewModel
    {

        public blog b { get; set; }
        public category c { get; set; }

        public blogViewModel()
        {
            this.b = new blog();
            this.c = new category();
        }
    }
}

EntAssignment/EntAssignment/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BusinessLogic;
using EntAssignment.BusinessLogic;
using EntAssignment.Common;
using EntAssignment.DataAccess;
using EntAssignment.Models;

namespace EntAssignment.Controllers
{
    public class BlogController : Controller
    {
        private codeMeEntities db = new codeMeEntities();

        // GET: Blog
        //public ActionResult Index()
        //{
        //    return View(db.blogs.Where(x=>x.authorId == User.Identity.Name).ToList());
        //}

        // GET: Blog/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            blog blog = db.blogs.Find(id);
            category c = db.categories.Find(blog.categoryId);

            if (blog == null)
            {
                return HttpNotFound();
            }

            blogViewModel bg = new blogViewModel();
            bg.b = blog;
            bg.c = c;

            return View(bg);
        }
        
        // GET: Blog/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Blog/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(blog blog,HttpPostedFileBase file)
        {
            string ImageName = System.IO.Path.GetFileName(file.FileName);
            string physicalPath = Server.MapPath("~/images/" + ImageName);


            AuthorController ac = new AuthorController();
            AuthorRepo ar = new AuthorRepo();
            if(ar.GetAuthor(User.Identity.Name) == null)
            {
                author a = new author();
                a.email = User.Identity.Name;
                ac.Create(a);
            }


            string path = "\\images\\";
            file.SaveAs(physicalPath);
            // save image in folder

            blog.Id = Guid.NewGuid();
            blog.publishDate = DateTime.Now;
            blog.authorId = User.Identity.Name;
            if(blog.tags == null)
            {
                blog.tags = "";
            }
            blog.imagePath = path + ImageName;

            if (ModelState.IsValid)
                {
                    db.blogs.Add(blog);
                    db.SaveChanges();
                    return RedirectToAction("Index","Home");
                }

            return RedirectToAction("Index","Home");
        }

        // GET: Blog/Edit/5
        [Authorize]
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            blog blog = db.blogs.Find(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // POST: Blog/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(blog blog)
        {
            var newContext = new codeMeEntities();

            blog b = db.blogs.Find(blog.Id);
            blog.imagePath = b.imagePath;
            blog.publishDate = b.publishDate;
            
            if (blog.tags == null)
            {
                blog.tags=b.tags;
            }

            if (ModelState.IsValid)
            {
                newContext.Entry(blog).State = EntityState.Modified;
                newContext.SaveChanges();
                return RedirectToAction("Index","Home");
            }
            return View(blog);
        }

        // GET: Blog/Delete/5
        [Authorize]
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            blog blog = db.blogs.Find(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // POST: Blog/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            blog blog = db.blogs.Find(id);
            db.blogs.Remove(blog);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EntAssignment/EntAssignment/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BusinessLogic;
using EntAssignment.BusinessLogic;
using EntAssignment.Common;
using EntAssignment.Models;

namespace EntAssignment.Controllers
{
    public class CategoryController : Controller
    {
        private codeMeEntities db = new codeMeEntities();

        [Route("/{id}")]
        public ActionResult Index(string id)
        {
            CategoryOperations co = new CategoryOperations();
            BlogOperations blogOps = new BlogOperations();
            if (id == "MVCNet")
            {
                id = "MVC.Net";
            }

            category c = co.GetCategory(id);
            blog firstBlog = blogOps.GetLatestBlog(c.name);
            List<blog> blogs = blogOps.GetLatestBlogs(c.name);

            CategoryViewModel model = new CategoryViewModel();
            model.c = c;
            model.b = blogs;
            model.fb = firstBlog;

            return View(model);
        }

        // GET: categories/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            category category = db.categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: categories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,name")] category category)
        {
            if (ModelState.IsValid)
            {
                category.Id = Guid.NewGuid();
                db.categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: categories/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            category category = db.categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,name")] category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: categories/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            category category = db.categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            category category = db.categories.Find(id);
            db.categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EntAssignment/EntAssignment/Views/Blog/Category.cshtml
@model EntAssignment.Models.CategoryViewModel

@{
    ViewBag.Title = "Category";
}


<h2>@Html.DisplayFor(m => m.c.name)</h2>
<br />

@foreach (var item in Model.fb)
{
    <div style="text-align:center">
        <h3><a href="/Blog/Details/@item.Id">@item.heading</a></h3> 
        <br />
        <img src="@item.imagePath" style="width:600px"/>
    </div>

    <br />
}

<table class="table">
    <tr>
        <th>
            Title
        </th>
        <th>
            Author
        </th>
        <th>
            Published On
        </th>
        <th>
            Tags
        </th>
    </tr>
    @foreach (var item in Model.b)
    {
        <tr>
            <td>
                <a href="/Blog/Details/" @item.Id>@Html.DisplayFor(modelItem => item.heading)</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.authorId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.publishDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.tags)
            </td>
        </tr>
    }

</table>


<h7>@Html.ActionLink("Write A Post", "Create")</h7>
| @Html.ActionLink("Back To Home", "Index", "Home")

EntAssignment/EntAssignment/Views/Blog/Create.cshtml
@model EntAssignment.Common.blog

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Blog", FormMethod.Post, new { enctype = "multipart/form-data" }) )
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.heading, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.heading, new { htmlAttributes = new { @class = "form-control", required = "required", maxlength = "50" } })
                @Html.ValidationMessageFor(model => model.heading, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.text, htmlAttributes: new { @class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.text, 5,130, new { htmlAttributes = new { @class = "form-control" }, required = "required" })
                @Html.ValidationMessageFor(model => model.text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
         
            <div class="col-md-10">
                <div class="form-group">
                    <label for="sel1">Category: </label>
                    <select class="form-control" name="categoryId" id="categoryId">
                        @foreach(var cat in new EntAssignment.BusinessLogic.CategoryOperations().GetCategories())
                        {
                            <option value="@cat.Id">@cat.name</option>
                        }
                    </select>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <input type="file" name="file" id="file" style="width: 100%;" required/>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tags, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tags, new { htmlAttributes = new { @class = "form-control"} })
                @Html.ValidationMessageFor(model => model.tags, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EntAssignment/EntAssignment/Views/Blog/Delete.cshtml
@model EntAssignment.Common.blog

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>blog</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.heading)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.heading)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.categoryId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.categoryId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.authorId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.authorId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.publishDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.publishDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.imagePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.imagePath)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tags)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tags)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EntAssignment/EntAssignment/Views/Blog/Details.cshtml
@model EntAssignment.Models.blogViewModel

@{
    ViewBag.Title = "Details";
}

<div>
    <div>
        <span style="float:left">
            <h4>@Html.DisplayFor(modelItem => Model.b.heading)</h4>
        </span>
        <span style="float:right">
            <h7 style="float:right">

                @{
                    if (Model.c.name == "MVC.Net")
                    {
                        <a href='@Url.Action("Index","Category",new { id = "MVCNet" })'>MVC.Net</a>
                    }
                    else if (Model.c.name == "C#")
                    {
                        <a href='@Url.Action("Index", "Category", new { id = "C#" })'>C#</a>
                    }
                    else if (Model.c.name == "JavaScript")
                    {
                        <a href='@Url.Action("Index", "Category", new { id = "JavaScript" })'>JavaScript</a>
                    }
                    else if (Model.c.name == "CSS")
                    {
                        <a href='@Url.Action("Index", "Category", new { id = "CSS" })'>CSS</a>
                    }
                }
        </span>
    </div>

    <br style="color:red"/>
    <dl class="dl-horizontal">

        <br />
        <br />

        <dd>
            <span style="float:left">Published on:  @Html.DisplayFor(model => model.b.publishDate)</span>


            <span style="float:right">
                <h7 style="float:right">
                    By
                    @{ var x = Model.b;
                        var author = x.authorId.Split('@').First();}
                    <a href="/Author/@author">
                        @Html.DisplayFor(modelItem => x.authorId)
                    </a>
            </span>
        </dd>

        <br />
        <br />

        <div style="margin-left:130px">
            <img src="@Model.b.imagePath" width="900" height="600">
        </div>



        <br />
        <br />

        <div style="padding-top:10px; padding-bottom:10px; font-size:18px;">
            @Html.DisplayFor(model => model.b.text)
        </div>


    </dl>
</div>

<p>
    @if (Model.b.authorId == User.Identity.Name)
    {
        @Html.ActionLink("Edit", "Edit", new { id = Model.b.Id })
    }
    |
    @Html.ActionLink("Back To Home", "Index", "Home")
</p>

EntAssignment/EntAssignment/Views/Blog/Edit.cshtml
@model EntAssignment.Common.blog

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>blog</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.heading, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.heading, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.heading, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.text, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.text, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.text, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">

        <div class="col-md-10">
            <div class="form-group">
                <label for="sel1">Category: </label>
                <select class="form-control" name="categoryId" id="categoryId">
                    @foreach (var cat in new EntAssignment.BusinessLogic.CategoryOperations().GetCategories())
                    {
                        <option value="@cat.Id">@cat.name</option>
                    }
                </select>
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.authorId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.authorId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.authorId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.tags, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.tags, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.tags, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index" ,"Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EntAssignment/EntAssignment/Views/Blog/Index.cshtml
@model IEnumerable<EntAssignment.Common.blog>

@{
    ViewBag.Title = "Index";
}

<h2>Blogs</h2>

@if (new BusinessLogic.BlogOperations().GetBlogsByUser(User.Identity.Name).Count > 0)
{
    <p style="float:right">
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                Title
            </th>
            <th>
                Author
            </th>
            <th>
                Published On
            </th>
            <th>
                Tags
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.heading)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.categoryId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.publishDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tags)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>
}
else
{

    <hr />
    <h3>You Have Not Written Any Posts Yet</h3>
    <br />
    <h4>@Html.ActionLink("Write A Post", "Create")</h4>
}